# We have to make sure turbolinks is loaded before we work our magic
document.addEventListener 'turbolinks:load', ->
  if document.getElementById('new-project-form')
    # Assign the elements we're intrerested in to variables
    openProjectButton = document.getElementById('new-project-button')
    projectPopover = document.getElementById('new-project-popover')
    projectForm = document.getElementById('new-project-form')
    projectName = document.getElementById('project-name-input')
    # Let's check to see if these elements exist before we add our listeners
    if openProjectButton and projectPopover
      # Attach an event listener to our new project button
      openProjectButton.addEventListener 'click', (->
        # If the project popovers class list contains the 'is-hidden' class, remove it
        # otherwise don't do anything!
        if projectPopover.classList.contains('is-hidden') then projectPopover.classList.remove('is-hidden') else null
      ), false
      # Attach an event listener to our cancel button
      cancelProjectPopover = document.getElementById('cancel-project-popover')
      cancelProjectPopover.addEventListener 'click', (->
        # We can safely assume that if our user can see the Cancel button, then the
        # .is-hidden class is not part of the class list of project pop-over and we can
        # remove it.
        projectPopover.classList.add 'is-hidden'
      ), false
    # Handle errors from the project form submission
    projectForm.addEventListener 'ajax:error', (xhr, status, err) ->
      # Have a good look at what's returned with a console.log()
      console.log xhr
      # Add an error class to the project name input
      projectName.classList.add 'is-invalid'
      # Create and add our error helper
      errorNode = document.createElement('div')
      errorTextNode = document.createTextNode('Name must not be blank')
      errorNode.classList.add 'invalid-feedback'
      errorNode.appendChild errorTextNode
      # Add the error message node using this ugly line of code. Thanks StackOverflow!
      projectName.parentNode.insertBefore errorNode, projectName.nextSibling
      return
  return

# ---
# generated by js2coffee 2.2.0
