document.addEventListener 'turbolinks:load', ->
  messageForm = document.getElementById('new-message-form')
  messageInput = document.getElementById('message-input')
  messageContainer = document.getElementById('chat-contents')

  if window.projectId and messageForm
    App.project_chat = App.cable.subscriptions.create({
      channel: 'ProjectChatChannel'
      room: window.projectId
    },
      connected: ->
        console.log 'Hello Channel!'
        # Called when the subscription is ready for use on the server
        return
      disconnected: ->
        # Called when the subscription has been terminated by the server
        return
      received: (data) ->
        messageNode = document.createElement('div')
        messageNode.innerHTML = data.message
        messageContainer.appendChild(messageNode)
        # Called when there's incoming data on the websocket for this channel
        return
      sendMessage: (message) ->
        @perform 'send_message',
          content: content
          project_id: window.projectId
        return

    messageForm.addEventListener 'submit', (e) ->
      e.preventDefault()
      App.project_chat.sendMessage messageInput.value
      messageInput.value = ''
      return
      )
  return

# ---
# generated by js2coffee 2.2.0
